[package]
authors = ["The Rust Project Developers"]
name = "arena"
version = "0.0.0"

[lib]
name = "arena"
path = "lib.rs"

[dependencies]
rustc_data_structures = { path = "../librustc_data_structures" }